import { PrismaClient } from "@prisma/client";
import { config } from "dotenv";

config();

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding database...");

  // Seed Billing Plans
  const starterPlan = await prisma.billingPlan.upsert({
    where: { name: "Starter" },
    update: {},
    create: {
      name: "Starter",
      stripePriceId: process.env.STRIPE_STARTER_PRICE_ID || null,
      priceCents: 999, // $9.99
      interval: "month",
      aiCredits: 100,
      features: JSON.stringify([
        "100 AI credits per month",
        "Basic resume templates",
        "PDF export",
        "Email support",
      ]),
      isActive: true,
    },
  });

  const proPlan = await prisma.billingPlan.upsert({
    where: { name: "Pro" },
    update: {},
    create: {
      name: "Pro",
      stripePriceId: process.env.STRIPE_PRO_PRICE_ID || null,
      priceCents: 2999, // $29.99
      interval: "month",
      aiCredits: -1, // Unlimited
      features: JSON.stringify([
        "Unlimited AI credits",
        "All premium templates",
        "Cover letter generator",
        "ATS optimization",
        "Priority support",
        "Resume analytics",
      ]),
      isActive: true,
    },
  });

  const teamPlan = await prisma.billingPlan.upsert({
    where: { name: "Team" },
    update: {},
    create: {
      name: "Team",
      stripePriceId: process.env.STRIPE_TEAM_PRICE_ID || null,
      priceCents: 9999, // $99.99
      interval: "month",
      aiCredits: -1, // Unlimited
      features: JSON.stringify([
        "Everything in Pro",
        "Shared workspaces",
        "Team collaboration",
        "Admin dashboard",
        "Custom branding",
        "Dedicated support",
        "API access",
      ]),
      isActive: true,
    },
  });

  console.log("✅ Billing plans seeded:", { starterPlan, proPlan, teamPlan });

  // Seed Resume Templates
  const modernTemplate = await prisma.resumeTemplate.upsert({
    where: { name: "Modern Professional" },
    update: {},
    create: {
      name: "Modern Professional",
      description:
        "Clean and modern design perfect for tech and creative industries",
      designJson: JSON.stringify({
        layout: "single-column",
        colors: { primary: "#6366f1", secondary: "#8b5cf6" },
        fonts: { heading: "Inter", body: "Open Sans" },
      }),
      thumbnail: "/templates/modern-professional.png",
      isPremium: false,
      isActive: true,
    },
  });

  const executiveTemplate = await prisma.resumeTemplate.upsert({
    where: { name: "Executive" },
    update: {},
    create: {
      name: "Executive",
      description: "Sophisticated design for senior-level positions",
      designJson: JSON.stringify({
        layout: "two-column",
        colors: { primary: "#1e293b", secondary: "#475569" },
        fonts: { heading: "Georgia", body: "Times New Roman" },
      }),
      thumbnail: "/templates/executive.png",
      isPremium: true,
      isActive: true,
    },
  });

  const creativeTemplate = await prisma.resumeTemplate.upsert({
    where: { name: "Creative" },
    update: {},
    create: {
      name: "Creative",
      description: "Bold and colorful design for creative professionals",
      designJson: JSON.stringify({
        layout: "asymmetric",
        colors: { primary: "#ec4899", secondary: "#f59e0b" },
        fonts: { heading: "Poppins", body: "Roboto" },
      }),
      thumbnail: "/templates/creative.png",
      isPremium: true,
      isActive: true,
    },
  });

  console.log("✅ Resume templates seeded:", {
    modernTemplate,
    executiveTemplate,
    creativeTemplate,
  });

  // Seed sample coupons
  const welcomeCoupon = await prisma.coupon.upsert({
    where: { code: "WELCOME2024" },
    update: {},
    create: {
      code: "WELCOME2024",
      type: "percentage",
      value: 20, // 20% off
      maxUses: 100,
      usedCount: 0,
      expiresAt: new Date("2024-12-31"),
      isActive: true,
    },
  });

  console.log("✅ Sample coupons seeded:", { welcomeCoupon });

  // Seed Test User
  const testUserEmail = "test@resumi.ai";
  const testUser = await prisma.user.upsert({
    where: { email: testUserEmail },
    update: {},
    create: {
      id: "test-user-id",
      name: "Test User",
      email: testUserEmail,
      emailVerified: true,
      image: "https://ui.shadcn.com/avatars/01.png",
    },
  });

  // Assign Pro Plan to Test User
  if (proPlan) {
    await prisma.subscription.upsert({
      where: { userId: testUser.id },
      update: {
        billingPlanId: proPlan.id,
        status: "active",
        currentPeriodEnd: new Date("2099-12-31"), // Lifetime access
      },
      create: {
        userId: testUser.id,
        billingPlanId: proPlan.id,
        status: "active",
        currentPeriodEnd: new Date("2099-12-31"),
      },
    });
  }

  // Create Account for Test User (Password: password123)
  // Note: This hash might need to be generated by better-auth's specific hashing algorithm
  // For now, we assume standard bcrypt or similar. If login fails, use "Forgot Password" or OAuth.
  // Using a placeholder hash that might not work directly without better-auth's salt logic.
  // Ideally, sign up manually and then run a script to upgrade to Pro.
  console.log(
    "✅ Test user seeded: test@resumi.ai (Password: password123 - might require reset)"
  );

  console.log("🎉 Database seeding completed!");
}

main()
  .catch((e) => {
    console.error("❌ Error seeding database:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
